name: 'wake up'

on:
  watch:
    types: started
  schedule:
    - cron: '*/20 0-15 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 'wakeup'
        run: |
          pwd
          ls -l
          python ./blog-cdn/py/wakeup.py
