name: 'wake up'

on:
  watch:
    types: started
  schedule:
    - cron: '*/20 0-15 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master
        with:
          submodules: "true"
      - name: 'wakeup'
        run: |
          python ./py/wakeup.py
